### ISSUE TITLE
How to change and upload configuration file?

### ISSUE THREAD

**Issue by nulant** [renedis/ubnt-auto-fan-speed#11]
Could you maybe please assist me how to make changes to the configuration file?
I would like to increase the minimum CPU fan % to decrease CPU temp.
It won't take my changes: MINPWM=hwmon0/device/pwm2=110.
Restart the service leads to: "Job for fancontrol.service failed because the control process exited with error code.
See "systemctl status fancontrol.service" and "journalctl -xe" for details."

Thank you in advance, Thomas

**Comment by renedis** [comment]
for easier editing install nano:
apt install nano

After that:
nano /etc/fancontrol

When you are done editing press CTRL+X and press Y and then ENTER to save the file.

restart the fancontrol service:
sudo service fancontrol restart
