### ISSUE TITLE
UniFi OS 4.0.3

### ISSUE THREAD

**Issue by mikkelxyz** [renedis/ubnt-auto-fan-speed#13]
First of, thanks for the work done on this project. 

I am on the early access program, and after installing last night, I immediately notice that my fan speed went up. 

Today, I tried reinstalling (using `curl -fsL "https://raw.githubusercontent.com/renedis/ubnt-auto-fan-speed/HEAD/on_boot.d/install.sh" | /bin/sh`, which worked perfectly for the initial installation), but now I get the error `ERROR: No persistent storage found`.

I know that 4.0.3 is not supported by this tool, but maybe it would be worth looking into it.

**Comment by renedis** [comment]
> First of, thanks for the work done on this project.
> 
> I am on the early access program, and after installing last night, I immediately notice that my fan speed went up.
> 
> Today, I tried reinstalling (using `curl -fsL "https://raw.githubusercontent.com/renedis/ubnt-auto-fan-speed/HEAD/on_boot.d/install.sh" | /bin/sh`, which worked perfectly for the initial installation), but now I get the error `ERROR: No persistent storage found`.
> 
> I know that 4.0.3 is not supported by this tool, but maybe it would be worth looking into it.

Thanks, I'm currently not on EA 4.0.3 but it sounds like the data DIR has changed.
I'm guessing that you came from version 3.x.x which has "/data" as check for the install path.

Maybe you can check via SSH what the default "data" dir is on firmware 4.0.3?

**Comment by renedis** [comment]
Updated one co-location to EA 4.0.3. Can't see any major changes why this would break support.

I've edited the script to support firmware 4.x.x, please run the script again and check if it works.

``
2*|3*|4*)
    DATA_DIR="/data"
    INSTALL_TYPE=2
    ;;
``

**Comment by mikkelxyz** [comment]
Seems to work perfectly 🥇 From `sensors`:
<img width="401" alt="image" src="https://github.com/renedis/ubnt-auto-fan-speed/assets/23260688/cecb9607-5cf5-4ab2-b93f-7e5cd0e07b87">
