### ISSUE TITLE
Temp2 and 3 might be swapped in the auto-fan-speed script

### ISSUE THREAD

**Issue by mariusbach** [renedis/ubnt-auto-fan-speed#3]
Hi, 

I noticed in the [11-ubnt-auto-fan-speed.sh](https://github.com/renedis/ubnt-auto-fan-speed/blob/16f559c39c69da2ff17a8dc6f79f810d95500dfa/on_boot.d/11-ubnt-auto-fan-speed.sh) script there might be temps swapped in the last paragraph. 

This is what currently is in the file:

`#######################################################################
#######################################################################

UBIOS_CPU_MINIMAL_TEMP='40000'       # default 45000, 45 degree celsius
UBIOS_HDD_MINIMAL_TEMP='40000'       # default 90000, 90 degree celsius
UBIOS_BRD_MINIMAL_TEMP='40000'       # default 90000, 90 degree celsius
UBIOS_CPU_MAXIMUM_TEMP='66000'       # default 72000, 72 degree celsius
UBIOS_HDD_MAXIMUM_TEMP='66000'       # default 112000, 112 degree celsius
UBIOS_BRD_MAXIMUM_TEMP='66000'       # default 112000, 112 degree celsius

echo ${UBIOS_CPU_MINIMAL_TEMP} >/sys/class/hwmon/hwmon0/device/temp1_auto_point1_temp
**echo ${UBIOS_HDD_MINIMAL_TEMP} >/sys/class/hwmon/hwmon0/device/temp3_auto_point1_temp
echo ${UBIOS_BRD_MINIMAL_TEMP} >/sys/class/hwmon/hwmon0/device/temp2_auto_point1_temp**
echo ${UBIOS_CPU_MAXIMUM_TEMP} >/sys/class/hwmon/hwmon0/device/temp1_auto_point2_temp
**echo ${UBIOS_HDD_MAXIMUM_TEMP} >/sys/class/hwmon/hwmon0/device/temp3_auto_point2_temp
echo ${UBIOS_BRD_MAXIMUM_TEMP} >/sys/class/hwmon/hwmon0/device/temp2_auto_point2_temp`**

Marked in bold is where I think there is a mistake, since I'm pretty confident that temp2 is assigned to HDD and temp3 is the BRD. Temp2 shows around 42-44degC for me while the other two temps are more in sync and rise with the CPU load. 

Perhaps I'm wrong but please double-check, that the temps are assigned correctly.

Thanks a lot!

Fyi: I'm on beta fw 1.12.30. All commands work, I just haven't tried to install the script as on-boot yet.

**Comment by borez** [comment]
Thanks for sharing! I just installed the script and checked sensor output on my UDMP, temp2 and temp3 seems to be correctly referenced.Cross checked the temps via the UDM GUI dashboard. Am running 1.12.30 production.

```
Adapter: i2c-0-mux (chan_id 3)
in1:          +0.89 V  (min =  +0.00 V, max =  +2.99 V)
+3.3V:        +3.27 V  (min =  +0.00 V, max =  +4.39 V)
fan1:        2040 RPM  (min =    0 RPM)
fan2:        1884 RPM  (min =    0 RPM)
fan3:           0 RPM  (min =    0 RPM)
fan4:           0 RPM  (min =    0 RPM)
temp1:        +46.2 C  (low  = -63.0 C, high = +191.0 C)
                       (crit = +100.0 C, hyst = +96.0 C)
Board Temp:   +44.2 C  (low  = -63.0 C, high = +191.0 C)
                       (crit = +100.0 C, hyst = +96.0 C)
temp3:        +45.2 C  (low  = -63.0 C, high = +191.0 C)
                       (crit = +100.0 C, hyst = +96.0 C)

```

**Comment by mariusbach** [comment]
Thanks for cross-checking. Let me share my data real quick:


```# sensors
adt7475-i2c-4-2e
Adapter: i2c-0-mux (chan_id 3)
in1:          +0.89 V  (min =  +0.00 V, max =  +2.99 V)
+3.3V:        +3.27 V  (min =  +0.00 V, max =  +4.39 V)
fan1:         919 RPM  (min =    0 RPM)
fan2:        1182 RPM  (min =    0 RPM)
fan3:           0 RPM  (min =    0 RPM)
fan4:           0 RPM  (min =    0 RPM)
temp1:        +56.2 C  (low  = -63.0 C, high = +191.0 C)
                       (crit = +100.0 C, hyst = +96.0 C)
Board Temp:   +52.2 C  (low  = -63.0 C, high = +191.0 C)
                       (crit = +100.0 C, hyst = +96.0 C)
temp3:        +55.5 C  (low  = -63.0 C, high = +191.0 C)
                       (crit = +100.0 C, hyst = +96.0 C)
```

While in the attached pic, you'll see the HDD temp mentioned in the GUI matching the board temp reported, not temp3. I'm confused :) 

Also, when I run the WifiMan app and use the signal mapper for throughput monitoring, the CPU will heat up and temp3. My guess is, that it's the board heating up along with the CPU, not the HDD (which in my case is a small SSD anyway). The GUI still reports the drive at 53.

That led me to assume the temp1 is CPU, temp2 is HDD and temp3 is board?
<img width="286" alt="SSD temp" src="https://user-images.githubusercontent.com/58884413/196703549-810faffa-44fc-4c1c-9ee4-a7d0c2a81019.png">

So while it may be that the HDD is heating up, as reported per temp3, it isn't the value the GUI shows. The GUI might be wrong though.

**Comment by mariusbach** [comment]
I'm on 1.12.30, forgot to mention.

**Comment by borez** [comment]
That's odd.. 

Am repurposing the HDD as a SMB share, doing some file copies and the HDD temperature spikes are mapping correctly to temp 3.

**Comment by renedis** [comment]
My temps are still showing correct values on 1.12.38

Working on 2.x.x version now.

**Comment by renedis** [comment]
Also on firmware 2.x.x (and 1.x.x):
temp1 = CPU
temp2 = BRD
temp3 = HDD
