### ISSUE TITLE
A massive THANK YOU!

### ISSUE THREAD

**Issue by othyn** [renedis/ubnt-auto-fan-speed#5]
Just wanted to say a massive thank you, the HDD fan noise on my UDM Pro has become an almost low pitch coil whine that just cuts through the room and burries into my brain, and easily out noises all the other equipment in my rack combined. After months and months of this ever so slowly getting worse, thought its finally time to do something about it.

You've provided much needed relief and its bliss, the rack is now silent, I'm astonished. Setting nice 50 degree minimums is acceptable temperature wise and allows the fans to run in silence, phenomenal.

Other option is to pickup a Noctua NF-A4x20 PWM 12v and hard mod it, but thought a soft mod would be better at this stage as its easily reversable.

So a massive, massive thank you to you!

**Comment by renedis** [comment]
Thank mate! much appreciated!
