### ISSUE TITLE
Support for UniFi OS - Dream Machine 2.4.23

### ISSUE THREAD

**Issue by mojo333** [renedis/ubnt-auto-fan-speed#6]
Any idea on how to get this working again for the latest UDM Pro version 2.4.23 which has moved to the same code base as the UDM SE?

The process S04ubnt-fan-speed no longer exists but something must be controlling the fans, as I removed the kill process for S04ubnt-fan-speed in the script but unfortunately the files being modified in the script seemed to be locked. I get
```
root@UDMP:/data/on_boot.d# ./20-auto-fan-speed.sh
sh: echo: I/O error
sh: echo: I/O error
```

The fans are running loud again so I'm very keen to sort this out.

**Comment by jmissig** [comment]
> The fans are running loud again so I'm very keen to sort this out.

This was going to be my first question — if Ubiquiti finally enabled auto fan speeds. Gutted to learn we’re going to have to work around this yet again.

Following this thread to learn more before I upgrade!

**Comment by paulschwahn** [comment]
At least for now you could set the fan speed manually without fan curves:


`echo 1 > /sys/class/hwmon/hwmon0/device/pwm1_enable`
`echo 1 > /sys/class/hwmon/hwmon0/device/pwm2_enable`
`echo 25 > /sys/class/hwmon/hwmon0/device/pwm1`
`echo 25 > /sys/class/hwmon/hwmon0/device/pwm2`

**Comment by mojo333** [comment]
This seemed to do the trick for now, thanks. At least the annoying noise is gone.

I just halved the current values I had so ended up with this which is now a lot quieter and tolerable:

```
echo 77 > /sys/class/hwmon/hwmon0/device/pwm1
echo 45 > /sys/class/hwmon/hwmon0/device/pwm2
```

**Comment by cdalvaro** [comment]
Any update on this issue??

**Comment by renedis** [comment]
> Any update on this issue??

Updated 2 days ago to 2.4.27..
trying to figure this thing out.

**Comment by renedis** [comment]
Solved by installing fancontrol. Working now on UDM-Pro with firmware 2.4.27.

Not tested on UDM-SE, but i can help out if someone gives me SSH access on a UDM-SE.

Made a pre-config and instructions for the UDM-Pro:
https://github.com/renedis/ubnt-auto-fan-speed/tree/main/on_boot.d

**Comment by cdalvaro** [comment]
Great work! Thank you very much!

**Comment by jmissig** [comment]
Wow thank you so much for continued effort on this. It’s the only thing I use on_boot.d for.
