### ISSUE TITLE
UDM-SE complete guide

### ISSUE THREAD

**Issue by mnsaddict** [renedis/ubnt-auto-fan-speed#7]
Can someone please post a complete guide on how to setup this on UDM SE v3.0.13.

Only need this to silence my udm-se.
Used it without any problems on my udm-pro since last week.
I m having trouble running podman and or other required things.

Found the following online but not sure till which part i should follow it.
https://di-marco.net/blog/it/2022-01-22-unchain_the_udm_pro_se/

Thanking you in advance!

**Comment by jmissig** [comment]
Most of this was made for UnifiOS 1.x, which works very differently from the current releases.

Fwiw what it’s worth the article you linked has a notice:

> The information in this article is for UniFi OS - Dream Machine SE [v2.5.11](https://community.ui.com/releases/UniFi-OS-Dream-Machine-SE-2-5-11/024e6e8a-9320-4583-b933-371f146e237b) or lower. And are unfortunately deprecated for UniFi OS SE [v3.0.13](https://community.ui.com/releases/UniFi-OS-Dream-Machine-SE-3-0-13/cf25f68e-6906-4125-9d77-9fce05d6658a).

**Comment by renedis** [comment]
Closing this issue. UDM-SE is not compatible (yet). Trying to figure out firmware 2.x.x first.
