### ISSUE TITLE
How to install on 2.x.x? (Could use some clarification, please)

### ISSUE THREAD

**Issue by waffles0042** [renedis/ubnt-auto-fan-speed#9]
Sorry for being so dense, but I am not quite clear how to install it on 2.x.x.

First hurdle: what needs to be installed in the on_boot.d folder (step 1)?

![image](https://user-images.githubusercontent.com/69690391/220787360-cf12cff0-a20e-4e75-8bd4-4dab73bf8df4.png)

(Second hurdle:)
So in my attempt, I left this step out, but followed step 2 and 3. When I tried to restart the fancontrol service I got an error message, which I tried to look up, as suggested:

`
Last login: Wed Feb 22 07:10:27 2023 from 192.168.1.115
root@UDM-Pro:# apt install fancontrol
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  fancontrol
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 45.4 kB of archives.
After this operation, 98.3 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main arm64 fancontrol all 1:3.4.0-4 [ 45.4 kB]
Fetched 45.4 kB in 0s (376 kB/s)
Selecting previously unselected package fancontrol.
(Reading database ... 53060 files and directories currently installed.)
Preparing to unpack .../fancontrol_1%3a3.4.0-4_all.deb ...
Unpacking fancontrol (1:3.4.0-4) ...
Setting up fancontrol (1:3.4.0-4) ...
Processing triggers for systemd (241-5 bpo9+1) ...
root@UDM-Pro:~# sudo service fancontrol restart
Job for fancontrol.service failed because the control process exited with error code.
See "systemctl status fancontrol.service" and "journalctl -xe" for details.
root@UDM-Pro:# ^C
root@UDM-Pro:# systemctl status fancontrol.service
● fancontrol.service - fan speed regulator
   Loaded: loaded (/lib/systemd/system/fancontrol.service; enabled; vendor prese
   Active: failed (Result: exit-code) since Wed 2023-02-22 18:27:39 EST; 1min 15
     Docs: man:fancontrol(8)
           man:pwmconfig(8)
  Process: 23251 ExecStartPre=/usr/sbin/fancontrol --check (code=exited, status=
      CPU: 74ms

Feb 22 18:27:39 UDM-Pro fancontrol[23251]: grep: /etc/fancontrol: Is a directory
Feb 22 18:27:39 UDM-Pro fancontrol[23251]: grep: /etc/fancontrol: Is a directory
Feb 22 18:27:39 UDM-Pro fancontrol[23251]: grep: /etc/fancontrol: Is a directory
Feb 22 18:27:39 UDM-Pro fancontrol[23251]: grep: /etc/fancontrol: Is a directory
Feb 22 18:27:39 UDM-Pro fancontrol[23251]: grep: /etc/fancontrol: Is a directory
Feb 22 18:27:39 UDM-Pro fancontrol[23251]: Some mandatory settings missing, plea
Feb 22 18:27:39 UDM-Pro systemd[1]: fancontrol.service: Control process exited,
Feb 22 18:27:39 UDM-Pro systemd[1]: fancontrol.service: Failed with result 'exit
Feb 22 18:27:39 UDM-Pro systemd[1]: Failed to start fan speed regulator.
Feb 22 18:27:39 UDM-Pro systemd[1]: fancontrol.service: Consumed 74ms CPU time.
lines 1-18/18 (END)...skipping...

~
`
Any help on what to do here would be greatly appreciated. Thanks!

**Comment by mojo333** [comment]
A few comments:
- Ignore `on_boot.d` for now - this may only be required for firmware updates where the `/etc` folder is reset. If this becomes an issue then repeat steps 1,3 and 4 below after you've installed the fancontrol package.
- this error `grep: /etc/fancontrol: Is a directory` says you've created a folder called `fancontrol `under `/etc` - `/etc/fancontrol` is a file not a folder. To fix this:

1. change directory to `/etc `by running the command `cd /etc`
2. remove the `fancontol` folder by running the command `rmdir fancontrol`
3. create the `fancontrol `file by running the command `wget https://raw.githubusercontent.com/renedis/ubnt-auto-fan-speed/main/on_boot.d/fancontrol`
4. restart the fancontrol service by running the command `service fancontrol restart`

Hope this helps.

**Comment by waffles0042** [comment]
Thank you very much, @mojo333 ; I followed your instructions. It installed and I was seemingly able to restart the fancontrol service  (no errors).  

=> how can I verify the service is running?
=> where can I find the configuration file with the parameters?

Thanks!

**Comment by mojo333** [comment]
Glad it worked. 

You can verify the service is running by running the command `service fancontrol status` - it should show the service as `active (running)`. Press `q` to exit the status report. 

You can view the configuration file by running the command `cat /etc/fancontrol` or if you want to edit it, `vi /etc/fancontrol`

**Comment by waffles0042** [comment]
Thanks @mojo333 ;

I don't think I have that file:
![image](https://user-images.githubusercontent.com/69690391/221255485-cc7fa92d-8b2c-4e6c-b342-1c4eac6d70b4.png)

I am looking in the correct folder, correct?


When I try to query the status I get this error:
![image](https://user-images.githubusercontent.com/69690391/221255198-dfa5821c-add2-4f97-911c-d3a43719e437.png)


So it seems like the install did not work (even though my UDMP is pretty quiet these days in the cold basement :-))

Any thoughts?

**Comment by mojo333** [comment]
Hmmm, it looks like step 2 failed for some reason.

Run steps 1 and 3 above. Once done, run the following command `ls fancontrol` and you should see something like
`root@UDMP:/etc# ls fancontrol`
`fancontrol`

If you do see the file listed above then run step 4 above to restart the fancontrol service.

**Comment by waffles0042** [comment]
@mojo333 ;

Thanks to your help, I think I now got it working:
![image](https://user-images.githubusercontent.com/69690391/221383319-85754d4a-b634-4019-81dd-cafa2ec8e896.png)

I my attempt before I executed step 3 while in the root directory and NOT in \etc. I wonder if this was the reason.

Again, THANK YOU SO MUCH FOR YOUR HELP!
